### ISSUE TITLE
whmcs 8.6.1

### ISSUE THREAD

**Issue by fedealex** [fedealvz/WHMCS-MercadoPago#10]
hola estimado, consulta, este modulo esta funcional en whmcs 8.6.1 ? no me carga la pasarela de pago y esta activo, si vas a modulo extras. la misma no te carga la licencia ni validación

saludos

**Comment by dgoyo** [comment]
A nosotros nos funciono sin problemas en 8.6.1 con php 8.1.

**Comment by fedealvz** [comment]
Hola @fedealex por acá también te confirmo que funciona bien 👍 
Este módulo no tiene licencia ni validación, quizás tenés el módulo anterior aún instalado y puede interferir.

**Comment by fedealex** [comment]
listo, como decía @fedealvz tenia rastros del modulo anterior, muchas gracias a todos ahora si esta funcional

**Comment by fedealvz** [comment]
Buenísimo! Gracias por confirmar Fede :)

**Comment by andersbocanegra** [comment]
> listo, como decía @fedealvz tenia rastros del modulo anterior, muchas gracias a todos ahora si esta funcional

Por favor me podrían indicar como es que borran estos rastros anteriores, a mi me aparece el tema de la licencia y ya me quedo claro que esta versión no cuenta con ello.

**Comment by gonzad26** [comment]
Hola!
Podes borrar el gateway de pago y el addon module anterior y después colocar los que están en este repositorio.

Saludos.
