### ISSUE TITLE
Solicitud/agradecimiento

### ISSUE THREAD

**Issue by Gjan1** [fedealvz/WHMCS-MercadoPago#12]
Primero que todo, muchas gracias por el modulo, estaba desesperado buscando un modulo de MercadoPago después de que Bayresapp desapareciera de un día para otro. 

También, quería consultar su está la posibilidad de solicitar  el modulo que tenía Bayresapp para DirectoPago (Ahora llamado dLocal). Puedo pagar por el modulo. 

Muchas gracias y saludos.

**Comment by fedealvz** [comment]
Disculpas no tengo módulos de Bayresapp, sólo hice este módulo basado en el de Mercadopago para que los colegas de hostings y resellers de hostings puedan seguir usando MercadoPago.
