### ISSUE TITLE
El IPN de notificaciones no funciona bien

### ISSUE THREAD

**Issue by AndyAlvarezDev** [fedealvz/WHMCS-MercadoPago#13]
Si bien, cuando pones el URL en mercadopago dice que se envió una notificación con éxito y dentro de la base de datos crea la tabla correspondiente al modulo de mercadopago, al efectuar un pago no graba la información, entonces el "Payment Status" siempre se mantendrá "Incomplete"...

**Comment by fedealvz** [comment]
Te sugiero revisar el access_log de tu servidor web, para determinar si entraron las peticiones de IPN de MercadoPago para confirmar el pago. De no hacerlo, o de darte algún error obviamente no guardará la transacción en la BD ni confirmará el pago en tu WHMCS.

Además te sugiero revisar el campo "WHMCS System URL" de tus General Settings ya que es la URL que le envía a MercadoPago para devolver luego el IPN.

**Comment by AndyAlvarezDev** [comment]
Esta todo normal, clone el proyecto y lo coloque en phpstorm y no hay manera, lo has probado tu últimamente? quizás hasta un tiempo atrás funcionaba y ahora no... a medida que la api de mercadopago actualiza hay que ir actualizando el código, en "notificaciones IPN" en mercadopago tengo colocado el url perfectamente y la respuesta es "200 - OK" pero si se hace una compra el pedido siempre permanece en "Incomplete"

**Comment by gonzad26** [comment]
Hola,
Yo lo tengo andando en mi WHMCS. 
Revisaste el system url de tu whmcs? Usa esa variable para armar la url de notificación.
Te recomendaría checkear el log de Apache para ver las peticiones entrantes a ver si entran y si podes también un var_dump de las preferencias de pago en el gateway para checkear lo que se está por mandar.
Como haces el proceso de pago? Desde el botón pagar de una invoice? completas el pago en modo sandbox con las tarjetas de crédito del modo sandbox para simular un pago?

Saludos
