### ISSUE TITLE
módulo no aprueba el producto

### ISSUE THREAD

**Issue by NellyOfc** [fedealvz/WHMCS-MercadoPago#17]
Alguien podría ayudarme, estoy teniendo un problema con el módulo, estoy en la versión whmcs 8.6, el módulo genera correctamente la factura, cuando la persona hace el pago el módulo no aprueba el producto

**Comment by gonzad26** [comment]
Hola!
No te entiendo el problema. Este módulo es un gateway de pago, no hace facturas. ¿a qué te réferis con no aprueba el producto?

Saludos.

**Comment by NellyOfc** [comment]
el sistema whmcs genera el pago correctamente desde el mercado pagado, realizo el pago, pero whmcs no recibe aprobación de pago y el producto aparece como pendiente

![image](https://user-images.githubusercontent.com/87354471/234164176-8967f228-f2c2-4e88-8bfe-55d083d7f55a.png)

**Comment by fedealvz** [comment]
Hola @NellyOfc 

Te sugiero que verifiques si subiste correctamente los [callback (IPN)](https://github.com/fedealvz/WHMCS-MercadoPago/tree/main/gateways/callback) y si son accesibles vía web, ya que MercadoPago envía a ellos las confirmaciones de pago.

Si eso está correcto y continuás sin recibir las confirmaciones de pago, podés ver el Gateway Log de tu WHMCS, o podés consultar al soporte de MercadoPago para que revisen el motivo por el que los callbacks no te llegan.
