### ISSUE TITLE
Errores luego de reemplazar archivos

### ISSUE THREAD

**Issue by alerickert** [fedealvz/WHMCS-MercadoPago#2]
Whoops\Exception\ErrorException: require_once(): Failed opening required '/home/clientes/public_html/modules/addons/mercadopago/../modules/gateways/MercadoPago_Lib/mercadopago_config.php' (include_path='.:/opt/cpanel/ea-php74/root/usr/share/pear') in /home/clientes/public_html/modules/addons/mercadopago/mercadopago.php:2
Stack trace:
#0 /home/clientes/public_html/vendor/whmcs/whmcs-foundation/lib/Utility/Error/Run.php(0): WHMCS\Utility\Error\Run->handleError(64, 'require_once():...', '/home/clientes/...', 2)
#1 [internal function]: WHMCS\Utility\Error\Run->handleShutdown()
#2 {main}

**Comment by fedealvz** [comment]
@alerickert te estaría faltando subir la carpeta "MercadoPago_Lib" dentro de la carpeta de gateways.
La estructura de archivos y carpetas debe quedar similar a como está publicada en el repo.

**Comment by alerickert** [comment]
Hola Fede, te hable por instagram.

Instale y de nuevo el mismo error pero lo solucioné.

El archivo en:  \addons\mercadopago\mercadopago.php en linea 2 dice:
require_once(__DIR__ . "/../modules/gateways/MercadoPago_Lib/mercadopago_config.php");

lo cambié por: require_once("./../modules/gateways/MercadoPago_Lib/mercadopago_config.php");

porque de la otra manera te poner mal la url y por eso no lo encuentra.


Quiero consultarte, modulo para mercadopago débito automatico? lo necesito.

**Comment by fedealvz** [comment]
@alerickert revisé el error y la única manera que ocurra es accediendo de forma directa a `/addons/mercadopago/mercadopago.php`, aunque no es la forma que se debe utilizar. Pronto le aplicaré un fix.

Actualmente no tiene feature de débito automático pero podés seguir el repo (Watch) para recibir notificaciones cuando se actualice:
![image](https://user-images.githubusercontent.com/32086536/203317530-d56bf4ff-b016-4600-9a6d-1a540e075ad4.png)

**Comment by fedealvz** [comment]
@alerickert lo siento, lo que mencionás no es open-soruce y no lo tengo desarrollado aún para este módulo. Si hay más feedback y más gente lo usa podría considerar implementarlo. Saludos!

**Comment by fedealvz** [comment]
Eso no tiene nada que ver con mi Github personal y no está a la venta, lo siento!
