### ISSUE TITLE
No me aparece el módulo

### ISSUE THREAD

**Issue by AngelRodriguezPineda** [fedealvz/WHMCS-MercadoPago#21]
Cuando entro al módulo solo me aparece esto: Todo lo sube en su lugar addons/mercadolibre y en gateways lo demas
![image](https://github.com/fedealvz/WHMCS-MercadoPago/assets/130931079/301b3e7d-51c3-4bda-bde2-318d2e6c6f01)

**Comment by gonzad26** [comment]
El addon module de WHMCS es solamente un placeholder para poder asociarse a eventos (hooks) del sistema por lo que vi en el código. Por eso solo se ve esto.

Saludos.
