### ISSUE TITLE
Cómo instalar el módulo

### ISSUE THREAD

**Issue by renato425** [fedealvz/WHMCS-MercadoPago#27]
Hola, estoy instalando tu módulo en un WHMCS 8.6, con PHP 8.1 y ionCube 13. Pero, ¿cómo lo instalo, ya que aparecen los módulos "Mercadopago", "Mercadopago 1", "Mercadopago 2", etc.?

**Comment by renato425** [comment]
Traducido con DeepL Translator

**Comment by villaboamiguel** [comment]
Hola!
Cada uno de los gateways que veas `"Mercadopago", "Mercadopago 1", "Mercadopago 2", etc.` son para que puedas utilizar N cuentas de Mercadopago en paralelo. Podes utilizar 1 solo de los gateways y va a estar todo bien.

Saludos!
