### ISSUE TITLE
Genera la factura pero al hacer click en el boton de pago no pasa nada

### ISSUE THREAD

**Issue by nathanro** [fedealvz/WHMCS-MercadoPago#28]
Hola, instale todo, cada cosa en su carpeta correspondiente.
Pero al momento de correrlo genera la factura. sale el boton de pagar pero lo unico que hace es recargar la factura.
Como puedo hacer para que abra la parte de pago?

**Comment by villaboamiguel** [comment]
Hola! No me queda claro cuando decís factura si te referís a la invoice de WHMCS.
Te fijaste en la consola del navegador si indica algún problema de javascript, me da la impresión que el problema va por ahí.

Saludos!

**Comment by nathanro** [comment]
si me refiero a la invoice
No me da un error de ningun tipo simplemente vuelve a cargar la invoice
no logro entender que me falta para que funcione.

**Comment by villaboamiguel** [comment]
Algún bloqueo generado por un adblocker?. Si el botón aparece significa que la transacción con Mercadopago funciono.

**Comment by nathanro** [comment]
no, el boton manda de regreso a view invoice
https://panel.ultrafast.host/viewinvoice.php?id=286
explico, se hace el pedido seleccionando mercado pago.
sale un boton, hago click y abre el invoice
en el invoice esta el logo de mercado pago y el boton de pagar ahora
el boton tiene una liga que manda a viewinvoice no manda a mercado pago a pagar

**Comment by nathanro** [comment]
ahorita tiene la api de pruebas
pero no creo que eso importe

**Comment by nathanro** [comment]
cambiando a stripe cambia la liga del boton a invoicepay
https://panel.ultrafast.host/invoice/286/pay
creo que hay algo en el script (seleccione mercadopago1) que no hace esa liga bien

**Comment by villaboamiguel** [comment]
Si inspeccionas el botón "Pagar ahora" tiene un link? Sino fíjate activando "Mostrar errores de MercadoPago" en la configuración del gateway a ver si te dice algo más. Recién lo estuve probando este gateway y me funciona correctamente. Quizás sea algo de configuración.

El link que pasaste para mirar pide login y no se puede ver la invoice.

**Comment by nathanro** [comment]
hola, como explique
El boton da a ver la invoice otra vez, "viewinvoice..."
en lugar de "invoice/numero/pay"
entonces vuelve a abrir el invoice una y otra vez

**Comment by jmzolezzi** [comment]
@nathanro lo que describis no tiene nada que ver con éste modulo, el cual funciona perfectamente. Revisaría tener WHMcs actualizado, usar el template básico, desactivar cualquier addon o cambio.
