### ISSUE TITLE
Problema con pagos en dólares.

### ISSUE THREAD

**Issue by ocasst** [fedealvz/WHMCS-MercadoPago#29]
Nosotros tenemos nuestros precios en dólares. Cuando alguien paga $170 pesos (como ejemplo) WHMCS marca la factura como pagada, pero como $170 dólares. ¿Hay alguna manera de evitar ese problema?

**Comment by villaboamiguel** [comment]
Hola!

Tenes correctamente configuradas las currencies en WHMCS. Me refiero más que nada a los ISO Code de las monedas. De esa manera al generar un pago MP deberia detectar la moneda. No estoy seguro si dolares toma igualmente Mercadopago. Lo mismo deberias tener creada la moneda de Pesos con el ISO Code y rate correctamente configurados para la conversión. Dicha conversión se genera si el ISO Code de la moneda del usuario es diferente a la de Mercadopago y la conversión es por el valor del rate.

Saludos!

**Comment by ocasst** [comment]
> Hola!
> 
> Tenes correctamente configuradas las currencies en WHMCS. Me refiero más que nada a los ISO Code de las monedas. De esa manera al generar un pago MP deberia detectar la moneda. No estoy seguro si dolares toma igualmente Mercadopago. Lo mismo deberias tener creada la moneda de Pesos con el ISO Code y rate correctamente configurados para la conversión. Dicha conversión se genera si el ISO Code de la moneda del usuario es diferente a la de Mercadopago y la conversión es por el valor del rate.
> 
> Saludos!

Hola, amigo, gracias, lo que sucede que solo usamos dólares, como moneda primaria. Lo que no queremos es usar muchas monedas diferentes, ya que tenemos clientes de diversos países. Usábamos antes otro módulo de PayU con el cual no teníamos problemas, solo que lo queremos reemplazar con MecadoPago, ya que esta otra empresa cambio mucho sus políticas. Ojalá hubiera aquí con nosotros algún desarrollador que nos pudiera echar la mano.

**Comment by JeanPal** [comment]
> > Hola!
> > Tenes correctamente configuradas las monedas en WHMCS. Me refiero más que nada a los Código ISO de las monedas. De esa manera al generar un pago MP deberíaria detectar la moneda. No estoy seguro si dólares toma igualmente Mercadopago. Lo mismo deberias tener creada la moneda de Pesos con el Código ISO y tasa correctamente configurada para la conversión. Dicha conversión se genera si el Código ISO de la moneda del usuario es diferente a la de Mercadopago y la conversión es por el valor del tipo.
> > ¡Saludos!
> 
> Hola amigo, gracias, lo que sucede que solo usamos dólares, como moneda primaria. Lo que no queremos es usar muchas monedas diferentes, ya que tenemos clientes de diversos países. Usábamos antes otro módulo de PayU con el cual no teníamos problemas, solo que lo queremos reemplazar con MecadoPago, ya que esta otra empresa cambia mucho sus políticas. Ojalá hubiera aquí con nosotros algún desarrollador que nos pudiera echar la mano.

Hola, sencillamente ve a 

https://github.com/fedealvz/WHMCS-MercadoPago/blob/main/gateways/MercadoPago_Lib/mercadopago_config.php

busca la linea 315 y cambia solo cambia esta parte "amountin" => $importe_pagado la cambias a "amountin" => $arr_datos_factura["balance"], y listo el pago en la factura del cliente se agregara en dolares y no en la moneda que usa mercadopago.. tambien puedes cambiar el fees a 0 como gustes

**Comment by Jeanlx** [comment]
> > Hola!
> > Tenes correctamente configuradas las currencies en WHMCS. Me refiero más que nada a los ISO Code de las monedas. De esa manera al generar un pago MP deberia detectar la moneda. No estoy seguro si dolares toma igualmente Mercadopago. Lo mismo deberias tener creada la moneda de Pesos con el ISO Code y rate correctamente configurados para la conversión. Dicha conversión se genera si el ISO Code de la moneda del usuario es diferente a la de Mercadopago y la conversión es por el valor del rate.
> > Saludos!
> 
> Hola, amigo, gracias, lo que sucede que solo usamos dólares, como moneda primaria. Lo que no queremos es usar muchas monedas diferentes, ya que tenemos clientes de diversos países. Usábamos antes otro módulo de PayU con el cual no teníamos problemas, solo que lo queremos reemplazar con MecadoPago, ya que esta otra empresa cambio mucho sus políticas. Ojalá hubiera aquí con nosotros algún desarrollador que nos pudiera echar la mano.

Hola, simplemente ve a

https://github.com/fedealvz/WHMCS-MercadoPago/blob/main/gateways/MercadoPago_Lib/mercadopago_config.php

busca la linea 315 y cambia solo cambia esta parte "amountin" => $importe_pagado la cambias a "amountin" => $arr_datos_factura["balance"], y listo el pago en la factura del cliente se agregara en dolares y no en la moneda que usa mercadopago.. tambien puedes cambiar el fee a 0 como gustesgregara en dolares y no en la moneda que usa mercadopago.. tambien puedes cambiar el fee a 0 como gustes

**Comment by fedealvz** [comment]
https://github.com/fedealvz/WHMCS-MercadoPago/issues/14
