### ISSUE TITLE
IPN dejó de funcionar en WHMcs 8.11

### ISSUE THREAD

**Issue by jmzolezzi** [fedealvz/WHMCS-MercadoPago#31]
Ayer actualizamos a WHMCs 8.11 y ahora no vemos los pagos acreditados de forma automática.

¿Alguien más actualizó y tuvo algún error?
¿Será un error con la nueva versión, o tendremos que ajustar algo como para tener la acreditación de pagos automática?

**Comment by villaboamiguel** [comment]
Te podrías fijar si en el System Activity Log hay alguna advertencia o algo en el procesamiento del id de referencia de pago o error para reconciliar el pago con la invoice? Cuando ocurre esto, suele incluir el texto addInvoicePayment.

**Comment by jmzolezzi** [comment]
Gracias @villaboamiguel, no veo ningún error en el System Activity Log.
En Gateway Transaction Log veo el pago Aprobado, pero no veo que la invoice sea marcada como pagada, como sucedía antes.

Tampoco veo errores de PHP ni nada raro en los logs.

Como empezó a suceder desde que actualizamos a WHMcs 8.11, asumo que será ese el error pero esperaré que algún otro corajudo / apresurado actualice para confirmar si es eso.

**Comment by diegovelasquez87** [comment]
Me pasa el mismo error al actualziar a la versión 8.11..

parece estar todo perfecto pero no se acreditan las facturas automáticamente.

han encontrado alguna solución?

**Comment by fedealvz** [comment]
@jmzolezzi @diegovelasquez87 gracias por el feedback! Corregido

**Comment by jmzolezzi** [comment]
Muchisimas gracias Fede!

**Comment by jmzolezzi** [comment]
Cerré el issue apresuradamente, pero aún no vemos los pagos acreditados automáticamente.

@diegovelasquez87 a vos te funcionó la actualización?

**Comment by diegovelasquez87** [comment]
> Cerré el issue apresuradamente, pero aún no vemos los pagos acreditados automáticamente.
> 
> @diegovelasquez87 a vos te funcionó la actualización?

Si, me funcionó perfecto a mi! Reemplacé solo el archivo modificado

**Comment by diegovelasquez87** [comment]
El archivo mercadopago_config.php para ser más exacto

**Comment by diegovelasquez87** [comment]
> Tenés razón, era un problema nuestro, el IPN funciona 10 puntos con la última versión.
> 
> Gracias por la confirmación @diegovelasquez87

De nada! Abrazo!

**Comment by fedealvz** [comment]
Hola @diegovelasquez87 ! Es buena idea!!! Te pido si te abrís un issue aparte para que sea visible

**Comment by mturcutto** [comment]
Gracias por la actualización. Mismo problema al actualizar a 8.11. No pude probar aún con el fix, pero dejo el agradecimiento de antemano.
