### ISSUE TITLE
No aparecen opciones canfigurables al instalar

### ISSUE THREAD

**Issue by marcoaguilar** [fedealvz/WHMCS-MercadoPago#33]
Hola! He cargado los archivos y habilitado el módulo en WHMCS, sin embargo al entrar en el Módulo, aparece sólo lo siguiente:

`MercadoPago
https://github.com/fedealvz/WHMCS-MercadoPago

Array
(
    [module] => mercadopago
    [modulelink] => addonmodules.php?module=mercadopago
    [access] => 4,1
    [version] => 17-remake
    [licencia] => 
    [verificador] => 
    [idioma] => ar
)`

También noté que en el área de Modulos Extra, aparece una opción para licencia, pero entiendo que es un módulo gratuito no? Podrían ayudar con esto? Gracias de antemano!

**Comment by fedealvz** [comment]
Hola @marcoaguilar ! Te respondo:

1. El Addon Module no tiene ninguna función para utilizar por el usuario, pero es parte del gateway para su correcto funcionamiento.

2. El campo "licencia" no es utilizado, pero se mantiene en la estructura para retrocompatibilidad de las versiones anteriores al remake.

**Comment by marcoaguilar** [comment]
Gracias @fedealvz , pero entonces ya no entendi nada. Dónde coloco los parámetros de MercadoPago? No me aparece la pantalla que viene en el ejemplo del marketplace. Sólo el código que compartí anteriormente. Me orientas por favor?

**Comment by fedealvz** [comment]
@marcoaguilar la configuración donde aplicas los parámetros de tu cuenta de MercadoPago se hace en la zona de configuración de las Gateways de WHMCS (Pasarelas de Pago).

El Addon Module se instala pero no tiene ninguna configuración, ni en el apartado de Addon Modules de WHMCS, ni en la pantalla que abre al abrir dicho addon.

**Comment by marcoaguilar** [comment]
@fedealvz Listo! ya me quedó claro muchas gracias! Parece estar funcionando correctamente. Excelente aporte!

**Comment by fedealvz** [comment]
Gracias @marcoaguilar !!! Si te sirvió por favor dale Star ⭐️ en Github y deja una reseña en el [Marketplace de WHMCS](https://marketplace.whmcs.com/product/6720-mercadopago-gateway#reviews) ✅ para soportar el proyecto :)

**Comment by lucaspef** [comment]
Hola, instalé los archivos en las carpetas respectivas pero no aparecen en mis gateways. ¿Hay algo específico que hacer?
