### ISSUE TITLE
Pagos recibidos correctamente pero facturas aún impagas

### ISSUE THREAD

**Issue by leandro-les** [fedealvz/WHMCS-MercadoPago#35]
Estimados, buenas!!
Quería consultarles acerca de un problema que estoy teniendo. El gateway de pagos funciona correctamente, las factuars se generan y se pueden pagar sin problemas.
Recibimos correctamente los pagos PERO, WHMCS sigue diciendo que la factura está impaga.

No se hizo ningún cambio en el servidor (ni actualización ni nada raro). No entendemos porqué dejó de funcionar.

¿alguna idea?.

No tenemos nada en el error_log, y en el access_log solo aparece esto:

```
54.88.218.97 - - [27/Oct/2024:20:56:32 -0300] "POST /modules/gateways/callback/mercadopago_1_ipn.php?data.id=91701544296&source_news=webhooks&type=payment HTTP/1.1" 200 5289 "https://mercadopago.com.ar" "MercadoPago WebHook v1.0 payment"
186.132.143.134 - - [27/Oct/2024:20:56:39 -0300] "GET /viewinvoice.php?id=155944&collection_id=91701544296&collection_status=approved&payment_id=91701544296&status=approved&external_reference=155944&payment_type=credit_card&merchant_order_id=24357510226&preference_id=4186241-210c7798-a186-4c81-8180-9345d1d3d806&site_id=MLA&processing_mode=aggregator&merchant_account_id=null HTTP/2.0" 200 11309 "https://www.mercadopago.com.ar/checkout/v1/payment/redirect/2e1eac7d-bd32-433c-b362-3816c7a48a87/congrats/approved/?preference-id=4186241-210c7798-a186-4c81-8180-9345d1d3d806&router-request-id=7fbcc877-92f8-4e96-8b77-d63321f209e7&p=8f106c34e790eea9ff1371ae673a7a54" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
```

Probamos también cambiando de versión del módulo e instalando esta: "WHMCS-MercadoPago-wip-fix-issue-34.zip".

Aún seguimos con el mismo problema.

Gracias!!

**Comment by villaboamiguel** [comment]
Hola!

Probaste con la ultima versión de release: https://github.com/fedealvz/WHMCS-MercadoPago/releases/tag/v17.2 que dice justamente que arregla eso?

Acá confirmaron que fue arreglado ese mismo problema: https://github.com/fedealvz/WHMCS-MercadoPago/issues/31

Saludos.

**Comment by leandro-les** [comment]
Hola buenas!! sinceramiente no había visto ese release. Lo probé y parece funcionar de 10.

Muchas gracias por tu tiempo!

> Hola!
> 
> Probaste con la ultima versión de release: https://github.com/fedealvz/WHMCS-MercadoPago/releases/tag/v17.2 que dice justamente que arregla eso?
> 
> Acá confirmaron que fue arreglado ese mismo problema: #31
> 
> Saludos.
