### ISSUE TITLE
Problema de ruta

### ISSUE THREAD

**Issue by bremen90** [fedealvz/WHMCS-MercadoPago#4]
Recientemente he instalado esta version sobrescribiendo la comercial y funciono todo bien, pero al ingresar al administrador de modulos me tiraba error, y al mismo tiempo al querer administrar dicho plugin lo mismo.

Lo he solucionado cambiando la ruta del archivo addons/mercadopago.php

`require_once(__DIR__ . "../../../../modules/gateways/MercadoPago_Lib/mercadopago_config.php");`

saludos

**Comment by fedealvz** [comment]
Hola @bremen90 ! Te hago unas preguntas para revisar:

1. ¿Qué versión de PHP estás usando?

2. ¿Estás usando cPanel u otro panel de control (cuál)?

3. ¿Podés probar utilizando esta línea en lugar de la que usaste para solucionarlo y contarme cómo te funcionó?

   ```php
   require_once(ROOTDIR . "/modules/gateways/MercadoPago_Lib/mercadopago_config.php");
   ```

Gracias!

**Comment by bremen90** [comment]
Hola,

1) Php 7.4.33
2) cPanel
3) Con la linea que indicas, funciona perfectamente.

Estuve viendo que le ocurrió también a otro usuario
https://github.com/fedealvz/WHMCS-MercadoPago/issues/2#issuecomment-1320704910

tal vez es algo random u algún problema con sobrescribir la versión comercial
Saludos!

**Comment by fedealvz** [comment]
Gracias @aleandrot y @bremen90 por el feedback! Acabo de publicar la corrección que reportaron. Saludos!
