### ISSUE TITLE
Instalado, error en widget, eliminado y ahora todo de 10!

### ISSUE THREAD

**Issue by webstower** [fedealvz/WHMCS-MercadoPago#5]
La empresa Bayresapp desapareció de buenas a primeras!

Encontré buscando esta version, la instalé y como a otros al principio tiraba error porque llamaba a un widget que se ve no se utiliza más. Asique lo borré y santo remedio, todo funciona ok. Gracias por recuperar el proyecto!

**Comment by fedealvz** [comment]
Gracias Eze!

Al parecer algunos tienen un Widget adicional instalado que lo deben desinstalar.
