### ISSUE TITLE
Tengo el modulo de debito automatico.

### ISSUE THREAD

**Issue by gruposhock** [fedealvz/WHMCS-MercadoPago#8]
Hola tengo el modulo de debito automatico de bayres , estaba funcionando normalmente y cuando se suspendio el hosting de ellos dejo de funcionar. 
A alguien le interesa tener el codigo para modificarlo o tratar de solucionar el problema en el funcionamiento del mismo? 

Saludos!

**Comment by fedealvz** [comment]
Hola @gruposhock genial! Si podés adjuntalo en una respuesta acá y lo revisamos a ver si se puede hacer algo.
¿Es un módulo aparte del de Mercado Pago tradicional (corre en paralelo)?

**Comment by fedealvz** [comment]
@gruposhock si alguien tiene este módulo y lo sube podemos analizarlo y ver si es posible agregarlo a este proyecto. Saludos!

**Comment by gruposhock** [comment]
Hola, te paso los archivos. 

Funciona todo pero tira error al no funcionar la web de ellos bayres. 

[modules.zip](https://github.com/fedealvz/WHMCS-MercadoPago/files/10469075/modules.zip)

El modulo lo compramos hace 2 años y funcionaba sin inconvenientes hasta diciembre.
